### ISSUE TITLE
The title screen's background image squeezes when the canvas is small

### ISSUE THREAD

**Issue by haykam821** [CommunityDiep/server#2]
This is what happens when you have a window with a different ratio than the image:

![Squeezing background image](https://user-images.githubusercontent.com/24855774/34328864-4a452096-e8ba-11e7-8b72-4ca00aaa5afd.png)

Diep.io simply shows the middle of the image when the frame is small:

![Cropping background image](https://user-images.githubusercontent.com/24855774/34328876-872aeefa-e8ba-11e7-9237-bdecb63d9191.png)

cDiep should do the latter for consistency and cleanliness of the interface.

**Comment by haykam821** [comment]
Commit a30612e fixes this somewhat, but now the image is very large.

**Comment by cx88** [comment]
Commit https://github.com/CommunityDiep/client/commit/872f4bc2ef1460e773bc4d1bdb42854f7a10a541 fixed this completely.
